services:
  database:
    build: ./database
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    env_file:
    - .env

  backend:
    build:
      context: ./backend
      target: ${BUILD_TARGET}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
      - 5555:5555                           #PRISMA STUDIO PORT FOR DEV
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
      - backend