services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
    - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"         #BACKEND PORT
    restart: unless-stopped
    volumes:
      - ./backend:/app:delegated
      - /app/node_modules
    env_file:
    - .env
    depends_on:
      - database