services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
    - .env

  backend:
    build: ./backend
    ports:
      - "3001:3001"         #BACKEND PORT
    restart: unless-stopped
    env_file:
    - .env
    depends_on:
      - database